apiVersion: v1
kind: Service
metadata:
  name: shutter-island-service
spec:
  type: NodePort
  selector:
    app: shutter-island
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
